### ISSUE TITLE
TypeScript: `fieldsAuto` + generics = cryptic type error

### ISSUE THREAD

**Issue by SimonAlling** [lydell/tiny-decoders#24]
This works as expected at run time:

```typescript
function recordContaining<T>(decodeT: Decoder<T>) {
  const recordDecoder: Decoder<{ foo: T }> = fieldsAuto({ foo: decodeT })
  return recordDecoder
}

recordContaining(boolean)({ foo: false })
```

But it doesn't type check:

```
error TS2322: Type 'Decoder<Expand<{ [P in undefined extends T ? "foo" : never]?: { foo: T; }[P]; } & { [P in undefined extends T ? never : "foo"]: { foo: T; }[P]; }>, unknown>' is not assignable to type 'Decoder<{ foo: T; }, unknown>'.
  Type 'Expand<{ [P in undefined extends T ? "foo" : never]?: { foo: T; }[P]; } & { [P in undefined extends T ? never : "foo"]: { foo: T; }[P]; }>' is not assignable to type '{ foo: T; }'.
    Property 'foo' is missing in type '{}' but required in type '{ foo: T; }'.

2   const recordDecoder: Decoder<{ foo: T }> = fieldsAuto({ foo: decodeT });
          ~~~~~~~~~~~~~
```

The type `{}` seems suspicious. Perhaps interestingly, the following change doesn't affect the _last line_ of the error message at all:

```diff
-  const recordDecoder: Decoder<{ foo: T }> = fieldsAuto({ foo: decodeT })
+  const recordDecoder: Decoder<{ foo: T }> = fieldsAuto({ foo: decodeT, bar: number })
```

I'm on TypeScript 4.9.5.

**Comment by lydell** [comment]
Yes, `fieldsAuto` + generics is broken. It’s due to `WithUndefinedAsOptional`, which is fundamentally broken. (We talked about this elsewhere once if you remember, when someone else reported a similar problem.)

I’ve solved this design mistake, and https://github.com/lydell/tiny-decoders/issues/22, in the [codec](https://github.com/lydell/tiny-decoders/compare/codec) branch. You probably won’t be able to see anything interesting in that diff, though, because it’s heavy WIP and features a new (but similar) API (with “codecs” instead of decoders).

The status of the branch is that I’m satisfied with the new API and have managed to make it work type wise. I now need to update documentation and tests, and fix bugs that the tests will uncover.

**Comment by SimonAlling** [comment]
Woah! That's a blazing-fast reply if ever I saw one – and surprisingly delightful at that! Eagerly awaiting tiny-decoders 8.0.0. :rocket:
