### ISSUE TITLE
Nullable type is marked as optional but is required

### ISSUE THREAD

**Issue by clevett** [lydell/tiny-decoders#25]
I am running into an error with a type that can be `boolean | null` .  Could it be related to issue #24 ?

```
Type error: Type 'Decoder<{ success?: boolean; }, unknown>' is not assignable to type 'Decoder<RollBase, unknown>'.
  Type '{  success?: boolean;  }' is not assignable to type 'RollBase'.
    Property 'success' is optional in type '{ success?: boolean; }' but required in type 'RollBase'.
    
  77 | export const diceRollResultDecoder = fieldsAuto<DiceRollResultType>({
  78 |   ...rollBase,
> 79 |   count: rollBaseDecoder, 
```

``` 
type RollBase = {
  success: boolean | null;
};

const rollBase = {
  success: nullable(boolean),
};

const rollBaseDecoder = fieldsAuto<RollBase>({
   ...rollBase,
});

const diceRollResultDecoder = fieldsAuto<DiceRollResultType>({
  ...rollBase,
  count: rollBaseDecoder,
});
```

**Comment by lydell** [comment]
Hi! Can you make a repo or gist that reproduces the problem, please? I can’t really follow the snippets you posted.

**Comment by clevett** [comment]
This from a repo that isn't open source so I can't link to it.  This error appears when building a NextJs app. VSCode doesn't report any Typescript errors and using this same code in a non-Next app works fine. Adding `ignoreBuildErrors` in [next.config.js](https://nextjs.org/docs/app/api-reference/next-config-js/typescript) will allow the code to build as expected.

The decoder error reports this key as optional, `{ success?: boolean; }` but the defined decoders use `success: nullable(boolean)` and the passed in type has `success: boolean | null`. Could the falsey value of null be causing an issue with the `fieldsAuto` ? Could the falsey value of null be setting the key to optional ?

**Comment by lydell** [comment]
When reporting issue on open source repos, it is not uncommon that maintainers ask for a repo or gist that reproduces the problem. That generally does _not_ mean your _real_ repo, even if it’s open source, because that’s too overwhelming for a maintainer to get into. Instead, it means creating a _new_ repo only for demonstrating the issue, which ideally is as small as possible. A cool thing about this approach is that you often find the problem yourself while working on the reproduction repo.

In this case, everything is too unclear for me to think about, unfortunately.

**Comment by clevett** [comment]
The error appear to be with Typescripts strict mode. Thanks for considering the question.
